[package]
name = "lang_macro_impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
syn = "2.0"
quote = "1.0"
lang_macro_core = { workspace = true }
