[package]
name = "lang_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
colored = { workspace = true, optional = true }
lang_macro = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[features]
default = ["cli"]
cli = ["dep:colored"]
no-color = ["colored/no-color"]

[lib]
doctest = false