[package]
name = "lang_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
lang_engine = { workspace = true, features = [] }

# logging
log = { workspace = true }
pretty_env_logger = { workspace = true }

[features]
default = []
no-color = ["lang_engine/no-color"]
