name: Run Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rustup and Cargo
        run: |
          rustup update nightly \
          && rustup default nightly \
          && rustup component add rust-src --toolchain nightly

      - uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v4

      - name: Run Tests
        run: ls -a && cargo test
